name: security
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "22 7 * * 2"  # UTC

jobs:
  call-unified:
    uses: your-org/your-repo/.github/workflows/unified-security.yml@main
    with:
      # 需要 DAST 再开；没 Dockerfile 就别传或保持默认
      enable_dast: false
      dockerfile_path: "Dockerfile"
      java_version: "21"
      upload_sarif_on: "push"   # push | always | never
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
