name: Trivy CI/CD Universal Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image from Current App
        run: docker build -t my-app:${{ github.sha }} .

      - name: Run Trivy on Built Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-app:${{ github.sha }}'
          format: json
          output: trivy-report.json

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-report
          path: trivy-report.json

  
  
