name: DAST Scan with ZAP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start DVWA with Docker Compose
        run: |
          docker compose up -d
          sleep 15  # 给 DVWA 启动一些时间

      - name: List Running Containers (Debug)
        run: docker ps

      # # 提前拉取镜像
      # - name: Pull ZAP Docker image explicitly
      #   run: docker pull owasp/zap2docker-stable

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:4280'
          artifacts_name: 'zap-baseline-report'

      # - name: Upload ZAP Report to GitHub Security tab
      #   uses: actions/upload-artifact@v3
      #   with:
      #     sarif_file: 'trivy-results.sarif'
